---
- name: Stop Firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Start and enable HTTPD service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Create /var/www/domain/ for domain config
  file:
    path: "/var/www/{{ domain }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'

- name: Create /var/www/domain/html for domain config
  file:
    path: "/var/www/{{ domain }}/html"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'

- name: Create /var/www/domain/log for domain config
  file:
    path: "/var/www/{{ domain }}/log"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'

- name: Copy index.html
  copy:
    src: "{{ index_html }}"
    dest: "/var/www/{{ domain }}/html/index.html"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'
  register: index_html

- name: Create info.php
  copy:
    content: "<?php phpinfo();"
    dest: "/var/www/{{ domain }}/html/info.php"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'
  register: phpinfo

- name: Create /etc/httpd/sites-available
  file:
    path: "/etc/httpd/sites-available"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'

- name: Create /etc/httpd/sites-enabled
  file:
    path: "/etc/httpd/sites-enabled"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'

- name: Append Optional files option on httpd.conf
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "IncludeOptional sites-enabled/*.conf"
  register: httpd_conf

- name: Copy conf file to /etc/httpd/sites-available/
  copy:
    src: "{{ centos_src }}"
    dest: "/etc/httpd/sites-available/{{ domain }}.conf"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0755'
  register: result

- name: Serve virtual host
  file:
    src: "/etc/httpd/sites-available/{{ domain }}.conf"
    dest: "/etc/httpd/sites-enabled/{{ domain }}.conf"
    state: link

- name: Install python-utils for semanage
  yum:
    name: policycoreutils-python-utils
    state: latest
    update_cache: yes

- name: Adjust apache policies
  seboolean:
    name: httpd_unified
    state: yes
    persistent: yes

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  when: index_html.changed or phpinfo.changed or result.changed