---
- name: Adding apt key Grafana (Ubuntu)
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add repo grafana to Apt (Ubuntu)
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Installing Grafana (Ubuntu)
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Start and Enable grafana (Ubuntu)
  service:
    name: grafana-server
    state: started